package TrabajoFrameworksBackendYMicroservicios.PortalPeliculas_Cliente.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Pais {
    REPÚBLICA_DOMINICANA("República Dominicana"),
    ESPAÑA("España"),
    AFGANISTÁN("Afganistán"),
    ALEMANIA("Alemania"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_Y_BARBUDA("Antigua y Barbuda"),
    ARABIA_SAUDITA("Arabia Saudita"),
    ARGELIA("Argelia"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIYÁN("Azerbaiyán"),
    BAHAMAS("Bahamas"),
    BAHREIN("Bahrein"),
    BANGLADÉS("Bangladés"),
    BARBADOS("Barbados"),
    BELICE("Belice"),
    BENIN("Benín"),
    BENÍN("Benín"),
    BIELORRUSIA("Bielorrusia"),
    BOLIVIA("Bolivia"),
    BOTSUANA("Botsuana"),
    BRASIL("Brasil"),
    BRUNÉI("Brunéi"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    BUTÁN("Bután"),
    BÉLGICA("Bélgica"),
    CABO_VERDE("Cabo Verde"),
    CAMBOYA("Camboya"),
    CAMERÚN("Camerún"),
    CANADA("Canadá"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    CHIPRE("Chipre"),
    COLOMBIA("Colombia"),
    COMORAS("Comoras"),
    CONGO("Congo"),
    COREA_DEL_NORTE("Corea del Norte"),
    COREA_DEL_SUR("Corea del Sur"),
    COSTA_DE_MARFIL("Costa de Marfil"),
    COSTA_RICA("Costa Rica"),
    CUBA("Cuba"),
    DINAMARCA("Dinamarca"),
    DOMINICA("Dominica"),
    ECUADOR("Ecuador"),
    EGIPTO("Egipto"),
    EL_SALVADOR("El Salvador"),
    EMIRATOS_ARABES_UNIDOS("Emiratos Árabes Unidos"),
    ERITREA("Eritrea"),
    ESLOVAQUIA("Eslovaquia"),
    ESLOVENIA("Eslovenia"),
    ESTADOS_UNIDOS("Estados Unidos"),
    ESTONIA("Estonia"),
    ESUATINI("Esuatini"),
    ETIOPÍA("Etiopía"),
    FILIPINAS("Filipinas"),
    FINLANDIA("Finlandia"),
    FIYI("Fiyi"),
    FRANCIA("Francia"),
    GABÓN("Gabón"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GRANADA("Granada"),
    GRECIA("Grecia"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEA_BISÁU("Guinea-Bisáu"),
    GUINEA_ECUATORIAL("Guinea Ecuatorial"),
    GUYANA("Guyana"),
    HAITÍ("Haití"),
    HOLANDA("Países Bajos"),
    HONDURAS("Honduras"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAK("Irak"),
    IRÁN("Irán"),
    ISLANDIA("Islandia"),
    ISLAS_MARSHALL("Islas Marshall"),
    ISRAEL("Israel"),
    ITALIA("Italia"),
    JAMAICA("Jamaica"),
    JAPON("Japón"),
    JORDANIA("Jordania"),
    KAZAJISTÁN("Kazajistán"),
    KENIA("Kenia"),
    KIRGUISTÁN("Kirguistán"),
    KIRIBATI("Kiribati"),
    KUWAIT("Kuwait"),
    LAOS("Laos"),
    LESOTO("Lesoto"),
    LETONIA("Letonia"),
    LIBANO("Líbano"),
    LIBERIA("Liberia"),
    LIBIA("Libia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituania"),
    LUXEMBURGO("Luxemburgo"),
    LÍBANO("Líbano"),
    MADAGASCAR("Madagascar"),
    MALASIA("Malasia"),
    MALAWI("Malawi"),
    MALDIVAS("Maldivas"),
    MALI("Mali"),
    MALTA("Malta"),
    MALÍ("Mali"),
    MARRUECOS("Marruecos"),
    MAURICIO("Mauricio"),
    MAURITANIA("Mauritania"),
    MAYOTTE("Mayotte"),
    MEXICO("México"),
    MICRONESIA("Micronesia"),
    MOLDAVIA("Moldavia"),
    MONGOLIA("Mongolia"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    MÓNACO("Mónaco"),
    NAMIBIA("Namibia"),
    NAURU("Nauru"),
    NEPAL("Nepal"),
    NICARAGUA("Nicaragua"),
    NIGERIA("Nigeria"),
    NORUEGA("Noruega"),
    NUEVA_ZELANDA("Nueva Zelanda"),
    NÍGER("Níger"),
    NÍGERIA("Nigeria"),
    OMÁN("Omán"),
    PALAU("Palau"),
    PANAMÁ("Panamá"),
    PAPÚA_NUEVA_GUINEA("Papúa Nueva Guinea"),
    PAQUISTÁN("Pakistán"),
    PERU("Perú"),
    POLONIA("Polonia"),
    PORTUGAL("Portugal"),
    PUERTO_RICO("Puerto Rico"),
    QATAR("Qatar"),
    REINO_UNIDO("Reino Unido"),
    REPÚBLICA_CENTROAFRICANA("República Centroafricana"),
    REPÚBLICA_DEMOCRÁTICA_DEL_CONGO("República Democrática del Congo"),
    REUNION("Reunión"),
    REUNIÓN("Reunión"),
    RUANDA("Ruanda"),
    RUSIA("Rusia"),
    SAHARA_OCCIDENTAL("Sahara Occidental"),
    SAMOA("Samoa"),
    SANTO_TOMÉ_Y_PRÍNCIPE("Santo Tomé y Príncipe"),
    SAN_CRISTÓBAL_Y_NIEVES("San Cristóbal y Nieves"),
    SAN_MARINO("San Marino"),
    SAN_VICENTE_Y_LAS_GRANADINAS("San Vicente y las Granadinas"),
    SAO_TOMÉ_Y_PRÍNCIPE("Santo Tomé y Príncipe"),
    SENEGAL("Senegal"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONA("Sierra Leona"),
    SINGAPUR("Singapur"),
    SIRIA("Siria"),
    SOMALIA("Somalia"),
    SRI_LANKA("Sri Lanka"),
    SUAZILANDIA("Suazilandia"), PARAGUAY("Paraguay"),
    SUDÁFRICA("Sudáfrica"),
    SUDÁN("Sudán"),
    SUDÁN_DEL_SUR("Sudán del Sur"),
    SUECIA("Suecia"),
    SUIZA("Suiza"),
    SURINAM("Surinam"),
    TAILANDIA("Tailandia"),
    TAIWÁN("Taiwán"),
    TANZANIA("Tanzania"),
    TAYIKISTÁN("Tayikistán"),
    TIMOR_ORIENTAL("Timor Oriental"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_Y_TOBAGO("Trinidad y Tobago"),
    TUNEZ("Túnez"),
    TURKMENISTÁN("Turkmenistán"),
    TURQUÍA("Turquía"),
    TUVALU("Tuvalu"),
    TÚNEZ("Túnez"),
    UCRANIA("Ucrania"),
    URUGUAY("Uruguay"),
    UZBEKISTÁN("Uzbekistán"),
    VANUATU("Vanuatu"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    YEMEN("Yemen"),
    ZAMBIA("Zambia"),
    ZIMBABUE("Zimbabue");


    private final String nombre;

    Pais(String nombre) {
        this.nombre = nombre;
    }

    @JsonValue
    public String getNombre() {
        return nombre;
    }

    @JsonCreator
    public static Pais forValue(String value) {
        for (Pais pais : values()) {
            if (pais.getNombre().equalsIgnoreCase(value)) {
                return pais;
            }
        }
        throw new IllegalArgumentException("Valor inválido para el enum Pais: " + value);
    }
}
